### ISSUE TITLE
'TypeAccessor.Get' on a type with a hidden property throws a System.ArgumentException with the message 'An item with the same key has already been added'

### ISSUE THREAD

**Issue by hugocomh** [KeRNeLith/ImmediateReflection#2]
Consider the code below:

```csharp
[Serializable]
public class Bar
{
    public int? Prop1 { get; set; }
    public string Prop2 { get; set; }
}

[Serializable]
public class Foo : Bar
{
    public new int Prop1 { get; set; }
}
```

When executing this line:

```csharp
TypeAccessor.Get<Foo>();
```

throws a `System.ArgumentException` with the message `An item with the same key has already been added` and with the stack below:

```
System.ArgumentException : An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at ImmediateReflection.ImmediateProperties.Init(IEnumerable`1 properties)
at ImmediateReflection.ImmediateProperties..ctor(IEnumerable`1 properties)
at ImmediateReflection.ImmediateType..ctor(Type type, BindingFlags flags)
at ImmediateReflection.CachesHandler.<>c__DisplayClass7_0.<GetImmediateType>b__0()
at ImmediateReflection.MemoryCache`2.GetOrCreate(TKey key, Func`1 valueFactory)
at ImmediateReflection.CachesHandler.GetImmediateType(Type type, BindingFlags flags)
at ImmediateReflection.TypeAccessor.Get(Type type, BindingFlags flags)
at ImmediateReflection.TypeAccessor.Get(Type type)
at ImmediateReflection.TypeAccessor.Get[T]()
...
```

*Note that with or without using the **new** keyword, the exception also happens.

**Comment by KeRNeLith** [comment]
Hello,

That's indeed a case that certainly lack of unit tests. I will look into it soon.
Meanwhile if you have a suggestion feel free to propose an MR.

**Comment by KeRNeLith** [comment]
@hugocomh I created a new version of the package ([1.6.0](https://www.nuget.org/packages/ImmediateReflection/1.6.0)) including the fix.

**Comment by hugocomh** [comment]
Great @KeRNeLith. Thank you.
